CREATE TABLE dim_store_dw (
    store_key               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name              VARCHAR2(50)  NOT NULL,
    store_address_1         VARCHAR2(100) NOT NULL,
    store_address_2         VARCHAR2(100),
    store_city              VARCHAR2(25)  NOT NULL,
    store_zip               VARCHAR2(10),
    store_state             VARCHAR2(50)  NOT NULL,
    store_class_of_trade    VARCHAR2(50),
    store_is_chain          CHAR(1) NOT NULL,
    store_chain_name        VARCHAR2(50)
);

CREATE TABLE dim_product_dw (
    product_key    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,          
    product_name   VARCHAR2(50) NOT NULL,           
    category       VARCHAR2(20)  NOT NULL,           
    sub_cat        VARCHAR2(20),                     
    brand          VARCHAR2(50)  NOT NULL,          
    flavour        VARCHAR2(20),                     
    product_size   VARCHAR2(20)  NOT NULL,           
    stock_quantity_code   VARCHAR2(20)  NOT NULL,           
    unit_of_measure  VARCHAR2(10)  NOT NULL,         
    unit_price     NUMBER(10,2)  NOT NULL 
);

CREATE TABLE dim_distributor_dw (
    dist_key    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      
    dist_name   VARCHAR2(50) NOT NULL,       
    dist_type   VARCHAR2(30) NOT NULL,       
    dist_city               VARCHAR2(30),                
    dist_state              VARCHAR2(30),
    dist_onboarding_date    DATE,
    dist_active_flag CHAR(1) NOT NULL
);

CREATE TABLE dim_date_dw(
    date_id        NUMBER PRIMARY KEY,   
    full_date       DATE        NOT NULL,    

    day             NUMBER(2)   NOT NULL,    
    day_name        VARCHAR2(10) NOT NULL,   

    week_of_year    NUMBER(2)   NOT NULL,    
    month           NUMBER(2)   NOT NULL,    
    month_name      VARCHAR2(10) NOT NULL,   

    quarter         NUMBER(1)   NOT NULL,    
    year            NUMBER(4)   NOT NULL,    

    is_weekend      CHAR(1)     NOT NULL     
);

CREATE TABLE fact_sales_dw (
    sales_key        NUMBER PRIMARY KEY,   

    date_id          NUMBER(8) NOT NULL,                

    store_key        NUMBER(10) NOT NULL,       
    product_key      NUMBER(10) NOT NULL,       
    dist_key         NUMBER(10) NOT NULL,       

    quantity_sold   NUMBER(10) NOT NULL,       
    unit_price      NUMBER(10,2) NOT NULL,     
    gross_amount    NUMBER(12,2) NOT NULL,     
    discount_amount NUMBER(10,2) DEFAULT 0,    
    net_amount      NUMBER(12,2) NOT NULL,     

    -- Foreign Key Constraints
    CONSTRAINT fk_sales_date
        FOREIGN KEY (date_id)
        REFERENCES dim_date_dw(date_id),

    CONSTRAINT fk_sales_store
        FOREIGN KEY (store_key)
        REFERENCES dim_store_dw(store_key),

    CONSTRAINT fk_sales_product
        FOREIGN KEY (product_key)
        REFERENCES dim_product_dw(product_key),

    CONSTRAINT fk_sales_distributor
        FOREIGN KEY (dist_key)
        REFERENCES dim_distributor_dw(dist_key)
);


ALTER TABLE dim_product_dw
ADD manufacturer VARCHAR2(50) NOT NULL;

select count(*) from dim_store_dw;
select * from dim_product_dw;

drop table dim_manufacturer;

CREATE TABLE dim_category (
    category_key      NUMBER PRIMARY KEY,
    category_name     VARCHAR2(100) NOT NULL
);

CREATE TABLE dim_sub_category (
    sub_category_key   NUMBER PRIMARY KEY,
    sub_category_name  VARCHAR2(100) NOT NULL
);

CREATE TABLE dim_manufacturer (
    manufacturer_key   NUMBER PRIMARY KEY,
    manufacturer_name  VARCHAR2(200) NOT NULL
);

CREATE TABLE dim_product_dw (
    product_key           NUMBER PRIMARY KEY,
    product_name          VARCHAR2(300) NOT NULL,
    category_key          NUMBER NOT NULL,
    sub_category_key      NUMBER NOT NULL,
    manufacturer_key      NUMBER NOT NULL,
    brand                 VARCHAR2(150) NOT NULL,
    flavour               VARCHAR2(100),
    product_size          VARCHAR2(50),
    stock_quantity_code   VARCHAR2(50),
    unit_of_measure       VARCHAR2(50),
    unit_price            NUMBER(10,2) NOT NULL
);

ALTER TABLE dim_product_dw
ADD CONSTRAINT fk_product_category
FOREIGN KEY (category_key)
REFERENCES dim_category (category_key);

ALTER TABLE dim_product_dw
ADD CONSTRAINT fk_product_sub_category
FOREIGN KEY (sub_category_key)
REFERENCES dim_sub_category (sub_category_key);

ALTER TABLE dim_product_dw
ADD CONSTRAINT fk_product_manufacturer
FOREIGN KEY (manufacturer_key)
REFERENCES dim_manufacturer (manufacturer_key);


CREATE TABLE dim_store_chain_dw (
    chain_key   NUMBER(10) PRIMARY KEY,
    chain_name  VARCHAR2(50) UNIQUE NOT NULL
);

ALTER TABLE dim_store_dw ADD (
    chain_key NUMBER(10)
);

ALTER TABLE dim_store_dw ADD CONSTRAINT fk_store_chain
FOREIGN KEY (chain_key)
REFERENCES dim_store_chain_dw(chain_key);

select * from fact_sales_dw;















